### ISSUE TITLE
Materialized views are fully refreshed

### ISSUE THREAD

**Issue by maxjoh** [risingwavelabs/dbt-risingwave#12]
From the dbt docs a `materialized view` and a `incremental` should only fully refresh if it does not already exist or if you supply the ´--full-refresh´ parameter.

- https://docs.getdbt.com/docs/build/materializations#materialized-view
- https://docs.getdbt.com/docs/build/incremental-models#how-do-i-rebuild-an-incremental-model

The risingwave docs says that it implements dbt's `incremental` mode i.e. https://docs.getdbt.com/docs/build/incremental-models but I'm not certain that it is implemented correctly.

In dbt-risingwave every time I run `dbt run`, all materialized views `{{ config(materialized='materializedview') }}` are dropped and re-created which is not expected when reading the official dbt documentation.

**Comment by chenzl25** [comment]
Different from other OLAP databases or data warehouses, they use dbt to do ELT. RisingWave is a streaming database, that can maintain a streaming pipeline increasingly in real-time, so you just need to run `dbt run` once unless you modify your models. That is the difference between an OLAP database and a streaming database.
