### ISSUE TITLE
use 'materialized_view' instead of 'materializedview'

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/dbt-risingwave#13]
https://docs.getdbt.com/blog/announcing-materialized-views dbt newly supports the materialized_view model in dbt-postgres. 

```jinja
{{
config(
     materialized='materialized_view',
)
}}
```

We should maintain the compatibility with other systems.

**Comment by chenzl25** [comment]
I know dbt 1.6 use `materialized_view` instead of `materializedview`, but we are using 1.5 right now. We will change it to `materialized_view` after we successfully bump dbt core to 1.6
