### ISSUE TITLE
Support dbt Core 1.7

### ISSUE THREAD

**Issue by james-johnston-thumbtack** [risingwavelabs/dbt-risingwave#30]
I would like to use a new feature in dbt Core 1.7.  Unfortunately the connector is only compatible with dbt 1.6: https://github.com/risingwavelabs/dbt-risingwave/blob/0339c2fef52702bfb16e25568a6d1f77ff052215/setup.py#L26

Would be nice if the support for dbt 1.7 can be added.

**Comment by james-johnston-thumbtack** [comment]
(for context, I'm looking to use the new `+access` configuration in dbt 1.7 to lock down all models in a subdirectory with `private` or `public` access modifier instead of the default `protected`.  in dbt 1.6 you have to set these one model at a time because there is no config)

**Comment by chenzl25** [comment]
Sure, we will upgrade to 1.7 ASAP.
